In [1]:
f = open("data/gapminder_gdp_oceania.csv","r")

In [2]:
f.read()

'country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007\nAustralia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744\nNew Zealand,10556.57566,12247.39532,13175.678,14463.91893,16046.03728,16233.7177,17632.4104,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911\n'

In [3]:
s = f.read()

In [4]:
print(s)

In [5]:
type(s)

str

In [6]:
print(s)

In [7]:
print(s)

In [8]:
f.close()

In [9]:
#f.read()

In [10]:
f = open("data/gapminder_gdp_oceania.csv","r")

In [11]:
s = f.read()

In [12]:
print(s)

country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744
New Zealand,10556.57566,12247.39532,13175.678,14463.91893,16046.03728,16233.7177,17632.4104,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911



In [13]:
#f.seek(0, SEEK_SET)

In [14]:
f.seek(0)

0

In [15]:
f.read()

'country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007\nAustralia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744\nNew Zealand,10556.57566,12247.39532,13175.678,14463.91893,16046.03728,16233.7177,17632.4104,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911\n'

In [16]:
f.tell

<function TextIOWrapper.tell()>

In [17]:
f.tell()

494

In [18]:
f.close()

In [19]:
s.split(",")

['country',
 'gdpPercap_1952',
 'gdpPercap_1957',
 'gdpPercap_1962',
 'gdpPercap_1967',
 'gdpPercap_1972',
 'gdpPercap_1977',
 'gdpPercap_1982',
 'gdpPercap_1987',
 'gdpPercap_1992',
 'gdpPercap_1997',
 'gdpPercap_2002',
 'gdpPercap_2007\nAustralia',
 '10039.59564',
 '10949.64959',
 '12217.22686',
 '14526.12465',
 '16788.62948',
 '18334.19751',
 '19477.00928',
 '21888.88903',
 '23424.76683',
 '26997.93657',
 '30687.75473',
 '34435.36744\nNew Zealand',
 '10556.57566',
 '12247.39532',
 '13175.678',
 '14463.91893',
 '16046.03728',
 '16233.7177',
 '17632.4104',
 '19007.19129',
 '18363.32494',
 '21050.41377',
 '23189.80135',
 '25185.00911\n']

In [20]:
s.split("\n")

['country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007',
 'Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744',
 'New Zealand,10556.57566,12247.39532,13175.678,14463.91893,16046.03728,16233.7177,17632.4104,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911',
 '']

In [21]:
s.split()

['country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007',
 'Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744',
 'New',
 'Zealand,10556.57566,12247.39532,13175.678,14463.91893,16046.03728,16233.7177,17632.4104,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911']

In [22]:
s.strip()

'country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007\nAustralia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744\nNew Zealand,10556.57566,12247.39532,13175.678,14463.91893,16046.03728,16233.7177,17632.4104,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911'

In [23]:
a = s.strip()

In [24]:
a.split()

['country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007',
 'Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744',
 'New',
 'Zealand,10556.57566,12247.39532,13175.678,14463.91893,16046.03728,16233.7177,17632.4104,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911']

In [25]:
a.split("\n")

['country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007',
 'Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744',
 'New Zealand,10556.57566,12247.39532,13175.678,14463.91893,16046.03728,16233.7177,17632.4104,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911']

In [26]:
s.strip().split("\n")

['country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007',
 'Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744',
 'New Zealand,10556.57566,12247.39532,13175.678,14463.91893,16046.03728,16233.7177,17632.4104,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911']

In [27]:
#s.split("\n").strip()

In [28]:
entries = []
for row in s.strip().split("\n"):
    for entry in row.split(","):
        entries.append(entry)

print(entries)

['country', 'gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967', 'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987', 'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007', 'Australia', '10039.59564', '10949.64959', '12217.22686', '14526.12465', '16788.62948', '18334.19751', '19477.00928', '21888.88903', '23424.76683', '26997.93657', '30687.75473', '34435.36744', 'New Zealand', '10556.57566', '12247.39532', '13175.678', '14463.91893', '16046.03728', '16233.7177', '17632.4104', '19007.19129', '18363.32494', '21050.41377', '23189.80135', '25185.00911']


In [29]:
entries = []
for row in s.strip().split("\n"):
    values = row.split(",")
    entries.append(values)

print(entries)

[['country', 'gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967', 'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987', 'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'], ['Australia', '10039.59564', '10949.64959', '12217.22686', '14526.12465', '16788.62948', '18334.19751', '19477.00928', '21888.88903', '23424.76683', '26997.93657', '30687.75473', '34435.36744'], ['New Zealand', '10556.57566', '12247.39532', '13175.678', '14463.91893', '16046.03728', '16233.7177', '17632.4104', '19007.19129', '18363.32494', '21050.41377', '23189.80135', '25185.00911']]


In [30]:
entries[1][1:]

['10039.59564',
 '10949.64959',
 '12217.22686',
 '14526.12465',
 '16788.62948',
 '18334.19751',
 '19477.00928',
 '21888.88903',
 '23424.76683',
 '26997.93657',
 '30687.75473',
 '34435.36744']

In [31]:
floats = []
for entry in entries[1][1:]:
    r = float(entry)
    floats.append(r)
print(floats)

[10039.59564, 10949.64959, 12217.22686, 14526.12465, 16788.62948, 18334.19751, 19477.00928, 21888.88903, 23424.76683, 26997.93657, 30687.75473, 34435.36744]


In [32]:
sum(floats)/len(floats)

19980.595634166668

In [33]:
s = 0
for country in entries[1:]:
    s += float(country[4])

s / (len(entries)-1)

14495.021789999999

In [34]:
l = []
for country in entries[1:]:
    l.append(float(country[4]))

sum(l) / (len(entries)-1)

14495.021789999999

In [35]:
#import pandas as pd
#pd.load_csv("./data/gapminder_gdp_oceania.csv")

In [36]:
#entries[1:][4]

In [37]:
import numpy

## introduce numpy

In [39]:
import numpy

In [41]:
numpy.loadtxt(skiprows=1,fname="data/gapminder_gdp_oceania.csv",usecols=range(1,13),delimiter=",")

array([[10039.59564, 10949.64959, 12217.22686, 14526.12465, 16788.62948,
        18334.19751, 19477.00928, 21888.88903, 23424.76683, 26997.93657,
        30687.75473, 34435.36744],
       [10556.57566, 12247.39532, 13175.678  , 14463.91893, 16046.03728,
        16233.7177 , 17632.4104 , 19007.19129, 18363.32494, 21050.41377,
        23189.80135, 25185.00911]])

In [46]:
variable0=numpy.loadtxt(skiprows=1,fname="data/gapminder_gdp_oceania.csv",usecols=range(1,13),delimiter=",")
rowzero=variable0[0]

array([10039.59564, 10949.64959, 12217.22686, 14526.12465, 16788.62948,
       18334.19751, 19477.00928, 21888.88903, 23424.76683, 26997.93657,
       30687.75473, 34435.36744])

In [52]:
type(rowzero)

numpy.ndarray

In [54]:
rowzero.mean()

np.float64(19980.595634166664)

In [59]:
variable0[0][0:]

array([10039.59564, 10949.64959, 12217.22686, 14526.12465, 16788.62948,
       18334.19751, 19477.00928, 21888.88903, 23424.76683, 26997.93657,
       30687.75473, 34435.36744])

In [60]:
entries[1:][4]

IndexError: list index out of range

In [64]:
entries[1:][0]

['Australia',
 '10039.59564',
 '10949.64959',
 '12217.22686',
 '14526.12465',
 '16788.62948',
 '18334.19751',
 '19477.00928',
 '21888.88903',
 '23424.76683',
 '26997.93657',
 '30687.75473',
 '34435.36744']

In [67]:
variable0[0:][0][3]

np.float64(14526.12465)

In [68]:
variable0[:,3]

array([14526.12465, 14463.91893])

In [69]:
fourthcolumbdata=variable0[:,3]
fourthcolumbdata.mean()

np.float64(14495.021789999999)

In [73]:
variable0[:,0]

array([10039.59564, 10556.57566])

In [74]:
variable0[0]

array([10039.59564, 10949.64959, 12217.22686, 14526.12465, 16788.62948,
       18334.19751, 19477.00928, 21888.88903, 23424.76683, 26997.93657,
       30687.75473, 34435.36744])

In [75]:
variable0[0,:]

array([10039.59564, 10949.64959, 12217.22686, 14526.12465, 16788.62948,
       18334.19751, 19477.00928, 21888.88903, 23424.76683, 26997.93657,
       30687.75473, 34435.36744])

In [76]:
variable0[0,...]

array([10039.59564, 10949.64959, 12217.22686, 14526.12465, 16788.62948,
       18334.19751, 19477.00928, 21888.88903, 23424.76683, 26997.93657,
       30687.75473, 34435.36744])

In [ ]:
timeit